name: CI
on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure
        run: cmake -S . -B build -DBUILD_TESTING=ON
      - name: Build
        run: cmake --build build -j 2
      - name: Test
        run: ctest --test-dir build --output-on-failure
